import { projects } from './projects.js';
import PhotoSwipeLightbox from 'photoswipe/lightbox';
import 'photoswipe/style.css';
import { animate } from 'motion';
const $=s=>document.querySelector(s);
if(import.meta.env.DEV && new URLSearchParams(location.search).has('qa')) import('./qa-audit.js');
let active=0,viewer=null,loading=false,loadToken=0,mode='assembly';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const dims=await fetch('/asset-sizes.json').then(r=>r.json()).catch(()=>({}));
function imageLink(name,caption,cls=''){const d=dims[name]||{width:1959,height:1124};return `<a class="${cls}" href="/images/${name}.webp" data-pswp-width="${d.width}" data-pswp-height="${d.height}" target="_blank" aria-label="Enlarge: ${caption}"><img src="/images/${name}-small.webp" srcset="/images/${name}-small.webp 700w, /images/${name}.webp ${d.width}w" sizes="(max-width: 760px) 94vw, 45vw" alt="${caption}" width="${d.width}" height="${d.height}" loading="lazy"></a>`;}
$('.project-tabs').innerHTML=projects.map((p,i)=>`<button class="project-tab" role="tab" id="tab-${p.id}" aria-controls="project-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-project="${i}"><span class="num">${p.number}</span><span><strong>${p.name}</strong><small>${p.category}</small></span></button>`).join('');
$('#case-studies').innerHTML=projects.map((p,i)=>`<article class="case" id="case-${p.id}"><div class="case-head"><div><p class="case-project">${p.name}</p><span class="case-category">${p.context}</span></div><h3>${p.title}</h3></div>${imageLink(...p.gallery[0],'case-hero')}<div class="case-text"><div><h4>The challenge</h4><p>${p.challenge}</p></div><div><h4>The design response</h4><p>${p.decision}</p></div></div><div class="gallery">${p.gallery.slice(1).map(([n,c])=>`<figure>${imageLink(n,c)}<figcaption>${c}</figcaption></figure>`).join('')}</div><div class="case-footer"><a class="text-link" href="#work" data-project="${i}">Explore ${p.name} in 3D ↑</a><span>Original portfolio · pages ${p.pages}</span></div></article>`).join('');
const lightbox=new PhotoSwipeLightbox({gallery:'#case-studies',children:'a[data-pswp-width]',pswpModule:()=>import('photoswipe'),showHideAnimationType:reduced?'none':'zoom'});lightbox.init();
function syncSelection(part){$('#part-name').textContent=part?.name||'Complete assembly';$('#part-description').textContent=part?.userData.description||'Select a component to frame it in the viewer.';$('#isolate').disabled=!part;$('#isolate').setAttribute('aria-pressed','false');$('.part-list').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.part===part?.name)));}
function showParts(parts){$('.part-list').replaceChildren(...parts.map(part=>{const b=document.createElement('button');b.textContent=part.name;b.dataset.part=part.name;b.setAttribute('aria-pressed','false');b.onclick=()=>viewer.select(part.name);return b;}));syncSelection(null);}
async function choose(i){active=i;loadToken++;const p=projects[i];document.documentElement.style.setProperty('--accent',p.accent);$('.project-tabs').querySelectorAll('button').forEach((b,j)=>{b.setAttribute('aria-selected',String(j===i));b.tabIndex=j===i?0:-1;});$('#project-panel').setAttribute('aria-labelledby',`tab-${p.id}`);$('#project-category').textContent=p.category;$('#project-name').textContent=p.name;$('#project-brief').textContent=p.brief;$('#case-link').textContent='Read the project ↓';$('#case-link').href=`#case-${p.id}`;$('#poster').src=`/images/${p.id}-hero.webp`;$('#poster').alt=p.gallery[0][1];$('#stage-label').textContent=`${p.name} / Component study`;$('#separation').value=0;$('#separation-value').value='0%';$('#explode').setAttribute('aria-pressed','false');$('#spin').setAttribute('aria-pressed','false');if(viewer&&!$('#viewer-controls').hidden)await start();}
async function start(){const token=++loadToken;loading=true;$('#canvas-host').hidden=false;$('#start-3d').hidden=true;$('#load-state').hidden=false;$('#load-state').textContent='Preparing the component study…';try{if(!viewer){const {createViewer}=await import('./viewer.js');if(token!==loadToken)return;viewer=createViewer($('#canvas-host'),syncSelection);}const parts=await viewer.load(projects[active].id,mode);if(token!==loadToken)return;showParts(parts);$('#stage-label').textContent=`${projects[active].name} / ${mode==='assembly'?'Component study':'Image reconstruction'}`;$('#explode').disabled=mode!=='assembly';$('#separation').disabled=mode!=='assembly';$('#poster').hidden=true;$('#load-state').hidden=true;$('#viewer-controls').hidden=false;$('#view-photo').hidden=false;$('.part-inspector').hidden=mode!=='assembly';$('.part-section').hidden=mode!=='assembly';viewer.resume();}catch(e){if(token!==loadToken)return;$('#load-state').textContent='3D is unavailable on this device. You can still explore the original images and project details below.';$('#canvas-host').hidden=true;$('#poster').hidden=false;$('#start-3d').hidden=false;$('#start-3d').textContent='Retry 3D';console.error(e);}finally{if(token===loadToken)loading=false;}}
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',async()=>{await choose(Number(b.dataset.project));if(b.tagName==='A')await start();}));
$('.project-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=e.key==='Home'?0:e.key==='End'?3:(active+(e.key==='ArrowRight'?1:3))%4;choose(i);$(`#tab-${projects[i].id}`).focus();});
$('#start-3d').onclick=start;
$('#view-photo').onclick=()=>{loadToken++;viewer?.pause();$('#canvas-host').hidden=true;$('#poster').hidden=false;$('#viewer-controls').hidden=true;$('#start-3d').hidden=false;$('#view-photo').hidden=true;$('#load-state').hidden=true;$('.part-inspector').hidden=true;$('.part-section').hidden=true;};
function separate(value){$('#separation').value=value;$('#separation-value').value=`${value}%`;$('#explode').setAttribute('aria-pressed',String(value>0));viewer?.explode(value/100);}
$('#separation').oninput=e=>separate(+e.target.value);$('#explode').onclick=()=>separate(+$('#separation').value>0?0:100);$('#reset').onclick=()=>{separate(0);viewer?.reset();$('#spin').setAttribute('aria-pressed','false');};$('#spin').onclick=()=>{const on=$('#spin').getAttribute('aria-pressed')!=='true';$('#spin').setAttribute('aria-pressed',String(on));viewer?.spin(on);};$('#zoom-in').onclick=()=>viewer?.zoom(.8);$('#zoom-out').onclick=()=>viewer?.zoom(1.25);$('#isolate').onclick=()=>{const on=$('#isolate').getAttribute('aria-pressed')!=='true';$('#isolate').setAttribute('aria-pressed',String(on));viewer?.isolate(on);};
choose(0);
if(!reduced)animate('.intro h1',{opacity:[0,1],y:[12,0]},{duration:.65});

$('#canvas-host').addEventListener('viewer-error',()=>{$('#view-photo').click();$('#load-state').hidden=false;$('#load-state').textContent='The 3D view stopped. Original portfolio images remain available.';});
